import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
cmd.c
strref.c
util.c
cyclequeue.c
""")

if GetDepend(['PKG_USING_U8G2']):
    src += Glob('sh1107_128128_4wire_hw_spi_example.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
