import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
at_tb22.c
at_cmd_rtu.c
at_cmd_uart.c
at_cmd_ulog.c
at_cmd_misc.c
util.c
strref.c
config.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
